---
- name: Install and configure GitLab CE
  hosts: all
  become: true
  vars:
    gitlab_external_url: "http://{{ ansible_host }}"
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - curl
          - openssh-server
          - ca-certificates
          - tzdata
        state: present

    - name: Add GitLab repository
      shell: |
        curl -fsSL https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
      args:
        warn: false

    - name: Install GitLab CE
      apt:
        name: gitlab-ce
        state: present

    - name: Configure GitLab external URL
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: '^external_url'
        line: "external_url '{{ gitlab_external_url }}'"

    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure

    - name: Ensure GitLab is running
      command: gitlab-ctl status
      register: gitlab_status

    - name: Fail if GitLab is not running
      fail:
        msg: "GitLab is not running. Check the logs for details."
      when: "gitlab_status.stdout.find('run:') == -1"
